language: go
go:
  - 1.3

install:
  - go get github.com/onsi/gomega
  - go get github.com/onsi/ginkgo
  - go install github.com/onsi/ginkgo/ginkgo
  - go get -t -v ./... || true
  - export PATH=$PATH:$HOME/gopath/bin

script: ginkgo -r --randomizeAllSpecs --failOnPending --randomizeSuites --race
